# Generated by Django 3.1.5 on 2021-02-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_post',
            field=models.BooleanField(default=False),
        ),
    ]
