# Generated by Django 3.1.5 on 2021-02-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210206_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='yt_url',
        ),
    ]
